//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServicesFromFour51.WRFour51Product {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ProductSoap", Namespace="http://four51.com/services/Product")]
    public partial class Product : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateProductInventoryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateMissingInteropIDsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePriceSchedulesOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeletePriceScheduleOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveCategoryAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteCategoryAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SavePriceScheduleAssignmentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveVariantsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteVariantsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchVariantsByProductOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListProductsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateMissingVariantInteropIDsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Product() {
            this.Url = global::ServicesFromFour51.Properties.Settings.Default.ServicesFromFour51_WRFour51Product_Product;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteProductCompletedEventHandler DeleteProductCompleted;
        
        /// <remarks/>
        public event UpdateProductInventoryCompletedEventHandler UpdateProductInventoryCompleted;
        
        /// <remarks/>
        public event GenerateMissingInteropIDsCompletedEventHandler GenerateMissingInteropIDsCompleted;
        
        /// <remarks/>
        public event SaveProductsCompletedEventHandler SaveProductsCompleted;
        
        /// <remarks/>
        public event SavePriceSchedulesCompletedEventHandler SavePriceSchedulesCompleted;
        
        /// <remarks/>
        public event DeletePriceScheduleCompletedEventHandler DeletePriceScheduleCompleted;
        
        /// <remarks/>
        public event SaveCategoryAssignmentsCompletedEventHandler SaveCategoryAssignmentsCompleted;
        
        /// <remarks/>
        public event DeleteCategoryAssignmentsCompletedEventHandler DeleteCategoryAssignmentsCompleted;
        
        /// <remarks/>
        public event SavePriceScheduleAssignmentsCompletedEventHandler SavePriceScheduleAssignmentsCompleted;
        
        /// <remarks/>
        public event SaveVariantsCompletedEventHandler SaveVariantsCompleted;
        
        /// <remarks/>
        public event DeleteVariantsCompletedEventHandler DeleteVariantsCompleted;
        
        /// <remarks/>
        public event SearchVariantsByProductCompletedEventHandler SearchVariantsByProductCompleted;
        
        /// <remarks/>
        public event ListProductsCompletedEventHandler ListProductsCompleted;
        
        /// <remarks/>
        public event GenerateMissingVariantInteropIDsCompletedEventHandler GenerateMissingVariantInteropIDsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/DeleteProduct", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] DeleteProduct(string[] ProductInteropIDs, string SharedSecret) {
            object[] results = this.Invoke("DeleteProduct", new object[] {
                        ProductInteropIDs,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProductAsync(string[] ProductInteropIDs, string SharedSecret) {
            this.DeleteProductAsync(ProductInteropIDs, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeleteProductAsync(string[] ProductInteropIDs, string SharedSecret, object userState) {
            if ((this.DeleteProductOperationCompleted == null)) {
                this.DeleteProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProductOperationCompleted);
            }
            this.InvokeAsync("DeleteProduct", new object[] {
                        ProductInteropIDs,
                        SharedSecret}, this.DeleteProductOperationCompleted, userState);
        }
        
        private void OnDeleteProductOperationCompleted(object arg) {
            if ((this.DeleteProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProductCompleted(this, new DeleteProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/UpdateProductInventory", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] UpdateProductInventory([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Inventory[] InventoryUpdates, string SharedSecret) {
            object[] results = this.Invoke("UpdateProductInventory", new object[] {
                        InventoryUpdates,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateProductInventoryAsync(Inventory[] InventoryUpdates, string SharedSecret) {
            this.UpdateProductInventoryAsync(InventoryUpdates, SharedSecret, null);
        }
        
        /// <remarks/>
        public void UpdateProductInventoryAsync(Inventory[] InventoryUpdates, string SharedSecret, object userState) {
            if ((this.UpdateProductInventoryOperationCompleted == null)) {
                this.UpdateProductInventoryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateProductInventoryOperationCompleted);
            }
            this.InvokeAsync("UpdateProductInventory", new object[] {
                        InventoryUpdates,
                        SharedSecret}, this.UpdateProductInventoryOperationCompleted, userState);
        }
        
        private void OnUpdateProductInventoryOperationCompleted(object arg) {
            if ((this.UpdateProductInventoryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateProductInventoryCompleted(this, new UpdateProductInventoryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/GenerateMissingInteropIDs", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateMissingInteropIDs(string SharedSecret) {
            this.Invoke("GenerateMissingInteropIDs", new object[] {
                        SharedSecret});
        }
        
        /// <remarks/>
        public void GenerateMissingInteropIDsAsync(string SharedSecret) {
            this.GenerateMissingInteropIDsAsync(SharedSecret, null);
        }
        
        /// <remarks/>
        public void GenerateMissingInteropIDsAsync(string SharedSecret, object userState) {
            if ((this.GenerateMissingInteropIDsOperationCompleted == null)) {
                this.GenerateMissingInteropIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateMissingInteropIDsOperationCompleted);
            }
            this.InvokeAsync("GenerateMissingInteropIDs", new object[] {
                        SharedSecret}, this.GenerateMissingInteropIDsOperationCompleted, userState);
        }
        
        private void OnGenerateMissingInteropIDsOperationCompleted(object arg) {
            if ((this.GenerateMissingInteropIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateMissingInteropIDsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SaveProducts", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SaveProducts([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ProductProperties[] Products, string SharedSecret) {
            object[] results = this.Invoke("SaveProducts", new object[] {
                        Products,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveProductsAsync(ProductProperties[] Products, string SharedSecret) {
            this.SaveProductsAsync(Products, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SaveProductsAsync(ProductProperties[] Products, string SharedSecret, object userState) {
            if ((this.SaveProductsOperationCompleted == null)) {
                this.SaveProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveProductsOperationCompleted);
            }
            this.InvokeAsync("SaveProducts", new object[] {
                        Products,
                        SharedSecret}, this.SaveProductsOperationCompleted, userState);
        }
        
        private void OnSaveProductsOperationCompleted(object arg) {
            if ((this.SaveProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveProductsCompleted(this, new SaveProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SavePriceSchedules", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SavePriceSchedules([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] PriceScheduleProperties[] PriceSchedules, string SharedSecret) {
            object[] results = this.Invoke("SavePriceSchedules", new object[] {
                        PriceSchedules,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SavePriceSchedulesAsync(PriceScheduleProperties[] PriceSchedules, string SharedSecret) {
            this.SavePriceSchedulesAsync(PriceSchedules, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SavePriceSchedulesAsync(PriceScheduleProperties[] PriceSchedules, string SharedSecret, object userState) {
            if ((this.SavePriceSchedulesOperationCompleted == null)) {
                this.SavePriceSchedulesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePriceSchedulesOperationCompleted);
            }
            this.InvokeAsync("SavePriceSchedules", new object[] {
                        PriceSchedules,
                        SharedSecret}, this.SavePriceSchedulesOperationCompleted, userState);
        }
        
        private void OnSavePriceSchedulesOperationCompleted(object arg) {
            if ((this.SavePriceSchedulesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePriceSchedulesCompleted(this, new SavePriceSchedulesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/DeletePriceSchedule", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] DeletePriceSchedule([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] PriceScheduleID[] PriceSchedules, string SharedSecret) {
            object[] results = this.Invoke("DeletePriceSchedule", new object[] {
                        PriceSchedules,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeletePriceScheduleAsync(PriceScheduleID[] PriceSchedules, string SharedSecret) {
            this.DeletePriceScheduleAsync(PriceSchedules, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeletePriceScheduleAsync(PriceScheduleID[] PriceSchedules, string SharedSecret, object userState) {
            if ((this.DeletePriceScheduleOperationCompleted == null)) {
                this.DeletePriceScheduleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeletePriceScheduleOperationCompleted);
            }
            this.InvokeAsync("DeletePriceSchedule", new object[] {
                        PriceSchedules,
                        SharedSecret}, this.DeletePriceScheduleOperationCompleted, userState);
        }
        
        private void OnDeletePriceScheduleOperationCompleted(object arg) {
            if ((this.DeletePriceScheduleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeletePriceScheduleCompleted(this, new DeletePriceScheduleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SaveCategoryAssignments", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SaveCategoryAssignments([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] CategoryAssignment[] CategoryAssignments, string SharedSecret) {
            object[] results = this.Invoke("SaveCategoryAssignments", new object[] {
                        CategoryAssignments,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveCategoryAssignmentsAsync(CategoryAssignment[] CategoryAssignments, string SharedSecret) {
            this.SaveCategoryAssignmentsAsync(CategoryAssignments, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SaveCategoryAssignmentsAsync(CategoryAssignment[] CategoryAssignments, string SharedSecret, object userState) {
            if ((this.SaveCategoryAssignmentsOperationCompleted == null)) {
                this.SaveCategoryAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveCategoryAssignmentsOperationCompleted);
            }
            this.InvokeAsync("SaveCategoryAssignments", new object[] {
                        CategoryAssignments,
                        SharedSecret}, this.SaveCategoryAssignmentsOperationCompleted, userState);
        }
        
        private void OnSaveCategoryAssignmentsOperationCompleted(object arg) {
            if ((this.SaveCategoryAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCategoryAssignmentsCompleted(this, new SaveCategoryAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/DeleteCategoryAssignments", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] DeleteCategoryAssignments([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] CategoryAssignment[] CategoryAssignments, string SharedSecret) {
            object[] results = this.Invoke("DeleteCategoryAssignments", new object[] {
                        CategoryAssignments,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCategoryAssignmentsAsync(CategoryAssignment[] CategoryAssignments, string SharedSecret) {
            this.DeleteCategoryAssignmentsAsync(CategoryAssignments, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeleteCategoryAssignmentsAsync(CategoryAssignment[] CategoryAssignments, string SharedSecret, object userState) {
            if ((this.DeleteCategoryAssignmentsOperationCompleted == null)) {
                this.DeleteCategoryAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCategoryAssignmentsOperationCompleted);
            }
            this.InvokeAsync("DeleteCategoryAssignments", new object[] {
                        CategoryAssignments,
                        SharedSecret}, this.DeleteCategoryAssignmentsOperationCompleted, userState);
        }
        
        private void OnDeleteCategoryAssignmentsOperationCompleted(object arg) {
            if ((this.DeleteCategoryAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCategoryAssignmentsCompleted(this, new DeleteCategoryAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SavePriceScheduleAssignments", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SavePriceScheduleAssignments([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] PriceScheduleAssignment[] PriceScheduleAssignments, string SharedSecret) {
            object[] results = this.Invoke("SavePriceScheduleAssignments", new object[] {
                        PriceScheduleAssignments,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SavePriceScheduleAssignmentsAsync(PriceScheduleAssignment[] PriceScheduleAssignments, string SharedSecret) {
            this.SavePriceScheduleAssignmentsAsync(PriceScheduleAssignments, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SavePriceScheduleAssignmentsAsync(PriceScheduleAssignment[] PriceScheduleAssignments, string SharedSecret, object userState) {
            if ((this.SavePriceScheduleAssignmentsOperationCompleted == null)) {
                this.SavePriceScheduleAssignmentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSavePriceScheduleAssignmentsOperationCompleted);
            }
            this.InvokeAsync("SavePriceScheduleAssignments", new object[] {
                        PriceScheduleAssignments,
                        SharedSecret}, this.SavePriceScheduleAssignmentsOperationCompleted, userState);
        }
        
        private void OnSavePriceScheduleAssignmentsOperationCompleted(object arg) {
            if ((this.SavePriceScheduleAssignmentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SavePriceScheduleAssignmentsCompleted(this, new SavePriceScheduleAssignmentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SaveVariants", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] SaveVariants([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] VariantProperties[] Variants, string SharedSecret) {
            object[] results = this.Invoke("SaveVariants", new object[] {
                        Variants,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void SaveVariantsAsync(VariantProperties[] Variants, string SharedSecret) {
            this.SaveVariantsAsync(Variants, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SaveVariantsAsync(VariantProperties[] Variants, string SharedSecret, object userState) {
            if ((this.SaveVariantsOperationCompleted == null)) {
                this.SaveVariantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveVariantsOperationCompleted);
            }
            this.InvokeAsync("SaveVariants", new object[] {
                        Variants,
                        SharedSecret}, this.SaveVariantsOperationCompleted, userState);
        }
        
        private void OnSaveVariantsOperationCompleted(object arg) {
            if ((this.SaveVariantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveVariantsCompleted(this, new SaveVariantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/DeleteVariants", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] DeleteVariants([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] VariantProperties[] Variants, string SharedSecret) {
            object[] results = this.Invoke("DeleteVariants", new object[] {
                        Variants,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void DeleteVariantsAsync(VariantProperties[] Variants, string SharedSecret) {
            this.DeleteVariantsAsync(Variants, SharedSecret, null);
        }
        
        /// <remarks/>
        public void DeleteVariantsAsync(VariantProperties[] Variants, string SharedSecret, object userState) {
            if ((this.DeleteVariantsOperationCompleted == null)) {
                this.DeleteVariantsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteVariantsOperationCompleted);
            }
            this.InvokeAsync("DeleteVariants", new object[] {
                        Variants,
                        SharedSecret}, this.DeleteVariantsOperationCompleted, userState);
        }
        
        private void OnDeleteVariantsOperationCompleted(object arg) {
            if ((this.DeleteVariantsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteVariantsCompleted(this, new DeleteVariantsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/SearchVariantsByProduct", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VariantProperties[] SearchVariantsByProduct(string[] ProductInteropIDs, string SharedSecret) {
            object[] results = this.Invoke("SearchVariantsByProduct", new object[] {
                        ProductInteropIDs,
                        SharedSecret});
            return ((VariantProperties[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchVariantsByProductAsync(string[] ProductInteropIDs, string SharedSecret) {
            this.SearchVariantsByProductAsync(ProductInteropIDs, SharedSecret, null);
        }
        
        /// <remarks/>
        public void SearchVariantsByProductAsync(string[] ProductInteropIDs, string SharedSecret, object userState) {
            if ((this.SearchVariantsByProductOperationCompleted == null)) {
                this.SearchVariantsByProductOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchVariantsByProductOperationCompleted);
            }
            this.InvokeAsync("SearchVariantsByProduct", new object[] {
                        ProductInteropIDs,
                        SharedSecret}, this.SearchVariantsByProductOperationCompleted, userState);
        }
        
        private void OnSearchVariantsByProductOperationCompleted(object arg) {
            if ((this.SearchVariantsByProductCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchVariantsByProductCompleted(this, new SearchVariantsByProductCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/ListProducts", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ProductProperties[] ListProducts(string SharedSecret) {
            object[] results = this.Invoke("ListProducts", new object[] {
                        SharedSecret});
            return ((ProductProperties[])(results[0]));
        }
        
        /// <remarks/>
        public void ListProductsAsync(string SharedSecret) {
            this.ListProductsAsync(SharedSecret, null);
        }
        
        /// <remarks/>
        public void ListProductsAsync(string SharedSecret, object userState) {
            if ((this.ListProductsOperationCompleted == null)) {
                this.ListProductsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListProductsOperationCompleted);
            }
            this.InvokeAsync("ListProducts", new object[] {
                        SharedSecret}, this.ListProductsOperationCompleted, userState);
        }
        
        private void OnListProductsOperationCompleted(object arg) {
            if ((this.ListProductsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListProductsCompleted(this, new ListProductsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://four51.com/services/Product/GenerateMissingVariantInteropIDs", RequestNamespace="http://four51.com/services/Product", ResponseNamespace="http://four51.com/services/Product", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ErrorReport[] GenerateMissingVariantInteropIDs(string[] ProductInteropIDs, string SharedSecret) {
            object[] results = this.Invoke("GenerateMissingVariantInteropIDs", new object[] {
                        ProductInteropIDs,
                        SharedSecret});
            return ((ErrorReport[])(results[0]));
        }
        
        /// <remarks/>
        public void GenerateMissingVariantInteropIDsAsync(string[] ProductInteropIDs, string SharedSecret) {
            this.GenerateMissingVariantInteropIDsAsync(ProductInteropIDs, SharedSecret, null);
        }
        
        /// <remarks/>
        public void GenerateMissingVariantInteropIDsAsync(string[] ProductInteropIDs, string SharedSecret, object userState) {
            if ((this.GenerateMissingVariantInteropIDsOperationCompleted == null)) {
                this.GenerateMissingVariantInteropIDsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateMissingVariantInteropIDsOperationCompleted);
            }
            this.InvokeAsync("GenerateMissingVariantInteropIDs", new object[] {
                        ProductInteropIDs,
                        SharedSecret}, this.GenerateMissingVariantInteropIDsOperationCompleted, userState);
        }
        
        private void OnGenerateMissingVariantInteropIDsOperationCompleted(object arg) {
            if ((this.GenerateMissingVariantInteropIDsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateMissingVariantInteropIDsCompleted(this, new GenerateMissingVariantInteropIDsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class ErrorReport {
        
        private string interopIDField;
        
        private string errorMessageField;
        
        /// <remarks/>
        public string InteropID {
            get {
                return this.interopIDField;
            }
            set {
                this.interopIDField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class PriceScheduleAssignment {
        
        private string productInteropIDField;
        
        private string variantInteropIDField;
        
        private string buyerCompanyInteropIDField;
        
        private PartyType assignmentLevelField;
        
        private string partyInteropIDField;
        
        private string standardOrderScheduleNameField;
        
        private string replenishmentOrderScheduleNameField;
        
        private string priceRequestOrderScheduleNameField;
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string VariantInteropID {
            get {
                return this.variantInteropIDField;
            }
            set {
                this.variantInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string BuyerCompanyInteropID {
            get {
                return this.buyerCompanyInteropIDField;
            }
            set {
                this.buyerCompanyInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public PartyType AssignmentLevel {
            get {
                return this.assignmentLevelField;
            }
            set {
                this.assignmentLevelField = value;
            }
        }
        
        /// <remarks/>
        public string PartyInteropID {
            get {
                return this.partyInteropIDField;
            }
            set {
                this.partyInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string StandardOrderScheduleName {
            get {
                return this.standardOrderScheduleNameField;
            }
            set {
                this.standardOrderScheduleNameField = value;
            }
        }
        
        /// <remarks/>
        public string ReplenishmentOrderScheduleName {
            get {
                return this.replenishmentOrderScheduleNameField;
            }
            set {
                this.replenishmentOrderScheduleNameField = value;
            }
        }
        
        /// <remarks/>
        public string PriceRequestOrderScheduleName {
            get {
                return this.priceRequestOrderScheduleNameField;
            }
            set {
                this.priceRequestOrderScheduleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public enum PartyType {
        
        /// <remarks/>
        User,
        
        /// <remarks/>
        Group,
        
        /// <remarks/>
        Company,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class CategoryAssignment {
        
        private string productInteropIDField;
        
        private string categoryInteropIDField;
        
        private System.Nullable<int> listOrderField;
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string CategoryInteropID {
            get {
                return this.categoryInteropIDField;
            }
            set {
                this.categoryInteropIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> ListOrder {
            get {
                return this.listOrderField;
            }
            set {
                this.listOrderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class PriceScheduleID {
        
        private string productInteropIDField;
        
        private string priceScheduleNameField;
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string PriceScheduleName {
            get {
                return this.priceScheduleNameField;
            }
            set {
                this.priceScheduleNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class PriceBreak {
        
        private int quantityField;
        
        private decimal priceField;
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class PriceScheduleProperties {
        
        private string productInteropIDField;
        
        private string nameField;
        
        private OrderType orderTypeField;
        
        private System.Nullable<bool> applySalesTaxField;
        
        private System.Nullable<bool> applyShippingField;
        
        private System.Nullable<bool> restrictedQuantitySelectionField;
        
        private System.Nullable<int> minimumQuantityField;
        
        private System.Nullable<int> maximumQuantityField;
        
        private PriceBreak[] priceBreaksField;
        
        private System.Nullable<bool> useCumulativeQuantityField;
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public OrderType OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ApplySalesTax {
            get {
                return this.applySalesTaxField;
            }
            set {
                this.applySalesTaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ApplyShipping {
            get {
                return this.applyShippingField;
            }
            set {
                this.applyShippingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> RestrictedQuantitySelection {
            get {
                return this.restrictedQuantitySelectionField;
            }
            set {
                this.restrictedQuantitySelectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MinimumQuantity {
            get {
                return this.minimumQuantityField;
            }
            set {
                this.minimumQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> MaximumQuantity {
            get {
                return this.maximumQuantityField;
            }
            set {
                this.maximumQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public PriceBreak[] PriceBreaks {
            get {
                return this.priceBreaksField;
            }
            set {
                this.priceBreaksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UseCumulativeQuantity {
            get {
                return this.useCumulativeQuantityField;
            }
            set {
                this.useCumulativeQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public enum OrderType {
        
        /// <remarks/>
        Standard,
        
        /// <remarks/>
        Replenishment,
        
        /// <remarks/>
        PriceRequest,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class VariantProperties {
        
        private string interopIDField;
        
        private string aPIInteropIDField;
        
        private string variantIDField;
        
        private string descriptionField;
        
        private string productInteropIDField;
        
        private ProductFile imageField;
        
        private System.Nullable<bool> activeField;
        
        private string newInteropIDField;
        
        /// <remarks/>
        public string InteropID {
            get {
                return this.interopIDField;
            }
            set {
                this.interopIDField = value;
            }
        }
        
        /// <remarks/>
        public string APIInteropID {
            get {
                return this.aPIInteropIDField;
            }
            set {
                this.aPIInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string VariantID {
            get {
                return this.variantIDField;
            }
            set {
                this.variantIDField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public ProductFile Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string NewInteropID {
            get {
                return this.newInteropIDField;
            }
            set {
                this.newInteropIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class ProductFile {
        
        private string fileNameField;
        
        private byte[] fileField;
        
        /// <remarks/>
        public string FileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] File {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class ProductProperties {
        
        private string aPIInteropIDField;
        
        private string interopIDField;
        
        private string newInteropIDField;
        
        private string productIDField;
        
        private string nameField;
        
        private string uNSPSCField;
        
        private string unitOfMeasureField;
        
        private string descriptionField;
        
        private ProductType typeField;
        
        private System.Nullable<bool> standardOrdersField;
        
        private System.Nullable<bool> replenishmentOrdersField;
        
        private System.Nullable<bool> priceRequestsField;
        
        private System.Nullable<int> quantityMultiplierField;
        
        private System.Nullable<decimal> shipWeightField;
        
        private System.Nullable<bool> trackInventoryField;
        
        private System.Nullable<bool> allowOrdersToExceedInventoryField;
        
        private System.Nullable<bool> useVariantLevelInventoryTrackingField;
        
        private System.Nullable<int> inventoryNotificationPointField;
        
        private System.Nullable<bool> displayInventoryToBuyerField;
        
        private ProductFile smallImageField;
        
        private ProductFile largeImageField;
        
        private System.Nullable<bool> activeField;
        
        private string outboundPunchoutTemplateNameField;
        
        private VariantProperties[] variantsField;
        
        /// <remarks/>
        public string APIInteropID {
            get {
                return this.aPIInteropIDField;
            }
            set {
                this.aPIInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string InteropID {
            get {
                return this.interopIDField;
            }
            set {
                this.interopIDField = value;
            }
        }
        
        /// <remarks/>
        public string NewInteropID {
            get {
                return this.newInteropIDField;
            }
            set {
                this.newInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string ProductID {
            get {
                return this.productIDField;
            }
            set {
                this.productIDField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string UNSPSC {
            get {
                return this.uNSPSCField;
            }
            set {
                this.uNSPSCField = value;
            }
        }
        
        /// <remarks/>
        public string UnitOfMeasure {
            get {
                return this.unitOfMeasureField;
            }
            set {
                this.unitOfMeasureField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public ProductType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> StandardOrders {
            get {
                return this.standardOrdersField;
            }
            set {
                this.standardOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> ReplenishmentOrders {
            get {
                return this.replenishmentOrdersField;
            }
            set {
                this.replenishmentOrdersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> PriceRequests {
            get {
                return this.priceRequestsField;
            }
            set {
                this.priceRequestsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> QuantityMultiplier {
            get {
                return this.quantityMultiplierField;
            }
            set {
                this.quantityMultiplierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> ShipWeight {
            get {
                return this.shipWeightField;
            }
            set {
                this.shipWeightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> TrackInventory {
            get {
                return this.trackInventoryField;
            }
            set {
                this.trackInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> AllowOrdersToExceedInventory {
            get {
                return this.allowOrdersToExceedInventoryField;
            }
            set {
                this.allowOrdersToExceedInventoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> UseVariantLevelInventoryTracking {
            get {
                return this.useVariantLevelInventoryTrackingField;
            }
            set {
                this.useVariantLevelInventoryTrackingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> InventoryNotificationPoint {
            get {
                return this.inventoryNotificationPointField;
            }
            set {
                this.inventoryNotificationPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DisplayInventoryToBuyer {
            get {
                return this.displayInventoryToBuyerField;
            }
            set {
                this.displayInventoryToBuyerField = value;
            }
        }
        
        /// <remarks/>
        public ProductFile SmallImage {
            get {
                return this.smallImageField;
            }
            set {
                this.smallImageField = value;
            }
        }
        
        /// <remarks/>
        public ProductFile LargeImage {
            get {
                return this.largeImageField;
            }
            set {
                this.largeImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        public string OutboundPunchoutTemplateName {
            get {
                return this.outboundPunchoutTemplateNameField;
            }
            set {
                this.outboundPunchoutTemplateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public VariantProperties[] Variants {
            get {
                return this.variantsField;
            }
            set {
                this.variantsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public enum ProductType {
        
        /// <remarks/>
        Static,
        
        /// <remarks/>
        VariableText,
        
        /// <remarks/>
        Kit,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://four51.com/services/Product")]
    public partial class Inventory {
        
        private string productInteropIDField;
        
        private string variantInteropIDField;
        
        private int availableQuantityField;
        
        private System.Nullable<bool> decrementByReservedQuantityField;
        
        /// <remarks/>
        public string ProductInteropID {
            get {
                return this.productInteropIDField;
            }
            set {
                this.productInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public string VariantInteropID {
            get {
                return this.variantInteropIDField;
            }
            set {
                this.variantInteropIDField = value;
            }
        }
        
        /// <remarks/>
        public int AvailableQuantity {
            get {
                return this.availableQuantityField;
            }
            set {
                this.availableQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> DecrementByReservedQuantity {
            get {
                return this.decrementByReservedQuantityField;
            }
            set {
                this.decrementByReservedQuantityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteProductCompletedEventHandler(object sender, DeleteProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void UpdateProductInventoryCompletedEventHandler(object sender, UpdateProductInventoryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateProductInventoryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateProductInventoryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerateMissingInteropIDsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SaveProductsCompletedEventHandler(object sender, SaveProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SavePriceSchedulesCompletedEventHandler(object sender, SavePriceSchedulesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePriceSchedulesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePriceSchedulesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeletePriceScheduleCompletedEventHandler(object sender, DeletePriceScheduleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeletePriceScheduleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeletePriceScheduleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SaveCategoryAssignmentsCompletedEventHandler(object sender, SaveCategoryAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCategoryAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCategoryAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteCategoryAssignmentsCompletedEventHandler(object sender, DeleteCategoryAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCategoryAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCategoryAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SavePriceScheduleAssignmentsCompletedEventHandler(object sender, SavePriceScheduleAssignmentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SavePriceScheduleAssignmentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SavePriceScheduleAssignmentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SaveVariantsCompletedEventHandler(object sender, SaveVariantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveVariantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveVariantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void DeleteVariantsCompletedEventHandler(object sender, DeleteVariantsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteVariantsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteVariantsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void SearchVariantsByProductCompletedEventHandler(object sender, SearchVariantsByProductCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchVariantsByProductCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchVariantsByProductCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VariantProperties[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VariantProperties[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void ListProductsCompletedEventHandler(object sender, ListProductsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListProductsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListProductsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ProductProperties[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ProductProperties[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void GenerateMissingVariantInteropIDsCompletedEventHandler(object sender, GenerateMissingVariantInteropIDsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateMissingVariantInteropIDsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateMissingVariantInteropIDsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ErrorReport[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ErrorReport[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591