// <auto-generated />
namespace EFClassLib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserNameTo50Lengths : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserNameTo50Lengths));
        
        string IMigrationMetadata.Id
        {
            get { return "201706050612412_UserNameTo50Lengths"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
